config/routes.rb
Rails.application.routes.draw do
  
  resources :items do
    member do
      patch :complete
    end
  end

  devise_for :users

  root 'welcome#index'
  
  get 'welcome/index'
  get 'about' => 'welcome/about'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  default_scope { order('created_at DESC')}

  def completed?
    !completed_at.blank?    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
  
  default_scope { order('created_at DESC')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.paginate(page: params[:page], per_page: 10)
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:notice] = 'Your new to-do was saved successfully.'
      redirect_to items_path
    else
      flash[:error] = 'Something went wrong. Your to-do was not saved.'
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params.require(:item).permit(:body, :complete))
      flash[:notice] = "Post was updated."
      redirect_to @item
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def complete
    @item = Item.find(params[:id])
    @item.update_attribute(:completed_at, Time.now)
    redirect_to items_path, notice: "Todo item marked as complete."
  end

  private

  def item_params
    params.require(:item).permit(:body, :complete)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/edit.html.erb
<div class="col-md-8">
 <%= form_for @item do |f| %>
   <div class="form-group">
     <%= f.label "Update todo" %>
     <%= f.text_area :body, rows: 1, class: 'form-control', placeholder: "Enter post body" %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>
</div>

app/views/items/index.html.erb
<h1>My To-do List</h1>

<table class="todo_items">
    <thead>
      <tr>
        <td class="col-md-4"><h4>Description</h4></td>
        <td class="col-md-2"><h4>Days left</h4></td>
        <td class="col-md-2"><h4>Complete</h4></td>
      </tr>
    </thead>

    <% @items.each do |item| %>
    <tr>
      <td class="col-md-4"><%= link_to item.body, item %></td>
      <td class="col-md-2"><%= 7 - (Time.now.to_date - item.created_at.to_date).to_i %></td>
      <td class="col-md-2">
        <% if item.completed? %>
          <%= item.completed_at %>
        <% else %>
          <%= link_to "Mark Complete", complete_item_path(item), method: :patch %>
        <% end %>
      </td>
    </tr>
    <% end %>
</table>

<%= link_to "Add a new todo", new_item_path, class: 'btn btn-success' %>

</br>

<%= will_paginate @items %>

app/views/items/new.html.erb
<div class="col-md-8">
 <%= form_for @item do |f| %>
   <div class="form-group">
     <%= f.label "Enter new todo" %>
     <%= f.text_area :body, rows: 1, class: 'form-control', placeholder: "Enter new todo" %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>
</div>

app/views/items/show.html.erb
</br>

<%= link_to "Edit", edit_item_path, class: 'btn btn-success' %>
 
<p><%= @item.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "My To-do List", items_path %></li>
      <li><%= link_to "Create a new todo", new_item_path %></li>
    
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= current_user.name %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  
  <%= yield %>

</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#app</h1>
<p>Find me in app/views/welcome/app.html.erb</p>

app/views/welcome/app.html.erb
<h1>Welcome#app</h1>
<p>Find me in app/views/welcome/app.html.erb</p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Blocitoff</h1>
  <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
      today!
  </p>
</div>